stages:
  - install
  - lint
  - test

variables:
  NODE_ENV: development

install:
  stage: install
  script:
    - npm ci
    - echo "✅ Dependencies installed."

lint:
  stage: lint
  script:
    - npm run lint

test:
  stage: test
  script:
    - node -v
